### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Rane90** [jason9693/MusicTransformer-pytorch#9]
RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 10.73 GiB total capacity; 9.03 GiB already allocated; 946.69 MiB free; 221.61 MiB cached)

I get this error, possibly by of my machine. Any idea how to solve this?

**Comment by adamoudad** [comment]
Either buy a new GPU, or decrease the model parameters.
The following configuration worked for me, in `config/base.yml`
```
experiment: 'embedding128-layer2'                                                                                                                                     
max_seq: 1024
embedding_dim: 128
num_layers: 2
event_dim: 388
fp16:
```
In `config/generate.yml`
```
save_path: 'bin/generated.mid'
condition_file:
length: 300
threshold_len: 200
```
Then run
`python train.py -c config/base.yml config/generate.yml config/train.yml -m model_dir`

**Comment by Rane90** [comment]
Thank you!
